---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/slides.md
  label: Presentation
  match: "**/*"
- type: heading
  label: Navigation
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: public
  publish_command: yarn build
  output_directory: public
